apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy: {}
  template:
    metadata:
      labels:
        app: kibana
    spec:
      hostname: kibana
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://es01:9200
          image: docker.elastic.co/kibana/kibana:7.1.1
          name: kibana
          ports:
            - containerPort: 5601
          resources: {}
      restartPolicy: Always
