apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-slave
  strategy: {}
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
        - args:
            - bash
            - -c
            - redis-server --slaveof $REDIS_MASTER_HOST 6379
          env:
            - name: REDIS_MASTER_HOST
              value: redis-master
          image: redis
          name: redis-slave
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
